lia: [int] = []
lib: [int] = [1,2,3]
lfa: [float] = []
lb: [bool] = [True,False,True]
tic: (int) = ()
tid: (int) = (1,2,3)
tfe: (float) = ()
tb: (bool) = (True,False,True)
sa: str = ""
sb: str = "hello!"
sc: str = '"quoted"'
sd: str = 'escaped\''
sd: str = "escaped \\ backslash"
sd: str = "more escaped '\"\\"
